selected_vm_label_stylesheet=("background-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:1, y2:0, stop:0 rgba(85, 40, 107, 255), stop:1 rgba(27, 28, 27, 255));\n"
    "border: none;")
apply_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(52, 53, 52);\n"
"    border:1px;\n"
"    border-style:outset;\n"
"    border-color:rgb(25, 26, 25);\n"
"    border-radius:5px\n;"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(62, 63, 62);\n"
"    border-color:rgb(35, 36, 35);\n"
"    border-radius:5px\n;"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(57, 58, 57);\n"
"    border-color:rgb(30, 31, 30);\n"
"    border-radius:5px\n;"
"}    ")
decorative_label_top_row_stylesheet=("background-color: rgb(52, 53, 52);\n"
"border:2px;\n"
"border-right:1px;\n"
"border-style:solid;\n"
"border-color:rgb(25,26,25);\n"
"")
rows_label_stylesheet=("background-color:transparent;\n"
"border: none;\n"
"")
columns_label_stylesheet=("background-color:transparent;\n"
"border: none;\n"
"")
selected_label_stylesheet=("background-color:transparent;\n"
    "border: none;")
cancel_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(52, 53, 52);\n"
"    border:1px;\n"
"    border-style:outset;\n"
"    border-color:rgb(25, 26, 25);\n"
"    border-radius:5px\n;"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(232, 17, 35);\n"
"    border-color: rgb(155, 26, 25);\n"
"    border-radius:5px\n;"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(149, 20, 30);\n"
"    border-color: rgb(95, 26, 25);\n"
"    border-radius:5px\n;"
"}    ")
rows_combobox_frame_stylesheet=("QFrame{\n"
"   background-color: rgb(25, 26, 25);\n"
"   color: rgb(236, 236, 236);\n"
"   selection-color: rgb(236, 236, 236);\n"
"   selection-background-color: rgb(52, 53, 52);\n"
"   outline: none;\n"
"   border:none"
"}\n"
"")
rows_combobox_stylesheet=("background-color: rgb(27, 28, 27);\n"
"color: rgb(236, 236, 236);\n"
"selection-color: rgb(236, 236, 236);\n"
"border: none;\n"
"selection-background-color: rgb(52, 53, 52);\n"
"\n"
"")
columns_combobox_frame_stylesheet=("QFrame{\n"
"   background-color: rgb(25, 26, 25);\n"
"   color: rgb(236, 236, 236);\n"
"   selection-color: rgb(236, 236, 236);\n"
"   selection-background-color: rgb(52, 53, 52);\n"
"   outline: none;\n"
"   border:none"
"}\n"
"")
columns_combobox_stylesheet=("background-color: rgb(27, 28, 27);\n"
"color: rgb(236, 236, 236);\n"
"selection-color: rgb(236, 236, 236);\n"
"border: none;\n"
"selection-background-color: rgb(52, 53, 52);\n"
"\n"
"")
decorative_label_top_row_2_stylesheet=("background-color: transparent;\n"
"border-left:2px;\n"
"border-right:2px;\n"
"border-style:solid;\n"
"border-color:rgb(25,26,25);")
selected_icon_label_stylesheet=("background-color: transparent;\n"
    "border: none;")