info_window_exit_button_stylesheet=("QPushButton {\n"
"    background-color: none;\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:none;\n"
"    margin:0px;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(232, 17, 35);\n"
"    border-style:solid;\n"
"    border-color:none;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(149, 20, 30);\n"
"    border-style:solid;\n"
"    border-color:none;    \n"
"}    \n"
"")
info_right_arrow_pushbutton_stylesheet=("background-color: transparent;\n"
"border:none;")
info_left_arrow_pushbutton_stylesheet=("background-color: transparent;\n"
"border:none;")