error_window_exit_button_stylesheet=("QPushButton {\n"
"    background-color: none;\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:none;\n"
"    margin:0px;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(232, 17, 35);\n"
"    border-style:solid;\n"
"    border-color:none;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(149, 20, 30);\n"
"    border-style:solid;\n"
"    border-color:none;    \n"
"}    \n"
"")
error_window_title_label_stylesheet=("color: rgb(232, 17, 35);\n"
"font: 16pt \"Alice\";\n"
"border-radius:5px;\n"
"border:none;\n"
"")
error_window_body_label_stylesheet=("border-radius: 5px;\n"
"color: rgb(236, 236, 236);\n"
"font: 10.5pt \"Alice\";"
"border-color:transparent;\n"
"")
error_window_ok_pushbutton_stylesheet=("QPushButton {\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"    background-color: rgb(29, 30, 29);\n"
"    border:1px;\n"
"    border-style:outset;\n"
"    border-color:rgb(29, 30, 29);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 43, 42);\n"
"    border-color:rgb(32, 33, 32);\n"
"    border-radius:5px\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(32, 33, 32);\n"
"    border-color:rgb(20, 21, 20);\n"
"    border-radius:5px;\n"
"}    ")