tab_widget_stylesheet=("QTabWidget::pane {\n"
"    border: 1px solid rgb(15, 16, 15);\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-bottom: 1px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    border-style: solid;\n"
"    border-bottom-color:  rgb(25, 26, 25);\n"
"    color:rgb(0,1,0);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: None;\n"
"    background-color: rgb(32, 33, 32);\n"

"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background-color: rgb(15, 16, 15);\n"

"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background-color: rgb(42,43,42);\n"

"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8px;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0, y2:0.00495455, stop:0 rgba(85, 40, 107, 255), stop:1 rgba(32, 33, 32, 255));\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8px;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
modify_selected_vector_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border:None;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 36, 35);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(29, 30, 29);\n"
"}    ")
vector_tree_widget_stylesheet=("QTreeWidget{\n"
"    border:None;\n"
"    background-color: rgb(25, 26, 25);\n"
"    outline:none;"
"}\n"
"QTreeWidget:item:hover{\n"
"    background-color: rgb(46, 35, 52);\n"
"}\n"
"QTreeWidget:item:selected:active:hover{\n"
"    background-color: rgb(80, 45, 107);\n"
"}\n"
"QTreeWidget:item:selected:hover{\n"
"    background-color: rgb(46, 35, 52);\n"
"}\n"
"QTreeWidget:item:selected:active{\n"
"    background-color: rgb(80, 45, 107);\n"
"}\n"
"QTreeWidget:item:selected{\n"
"    background-color: rgb(41, 30, 47);\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QHeaderView::section{\n"
"    border:none;\n"
"    color: rgb(236, 236, 236);\n"
"    background-color: rgb(32, 33, 32);\n"
"    font: 11pt \"Alice\";\n"
"}\n"
"\n"
"/* VERTICAL */\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 11px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
number_of_vector_label_stylesheet=("background-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:1, y2:0, stop:0 rgba(32, 33, 32, 255), stop:1 rgba(25, 26, 25, 255));\n"
"color: rgb(236, 236, 236);\n"
"border-bottom:0px;\n"
"border-left:0px;\n"
"border-top:0px;\n"
"border-style:solid;\n"
"border-left-color: rgb(85, 40, 107);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:1, y2:0, stop:0 rgba(15, 16, 15, 255), stop:1 rgba(25, 26, 25, 255));\n"
"border-top-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:1, y2:0, stop:0 rgba(85, 40, 107, 255), stop:1 rgba(25, 26, 25, 255));\n"
"")
number_of_vectors_combobox_frame_stylesheet=("QFrame{\n"
"   background-color: rgb(25, 26, 25);\n"
"   color: rgb(236, 236, 236);\n"
"   selection-color: rgb(236, 236, 236);\n"
"   selection-background-color: rgb(52, 53, 52);\n"
"   outline: none;\n"
"   border:none"
"}\n"
"")
number_of_vectors_combobox_stylesheet=("QComboBox{\n"
"   background-color: rgb(25, 26, 25);\n"
"   color: rgb(236, 236, 236);\n"
"   selection-color: rgb(236, 236, 236);\n"
"   selection-background-color: rgb(52, 53, 52);\n"
"   outline: none;\n"
"   border:none"
"}\n"
"\n"
"/* VERTICAL */\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 9px;\n"
"    margin: 9px 0 9px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 9px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 9px;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 11px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
modify_selected_matrix_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border:None;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 36, 35);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(29, 30, 29);\n"
"}    ")
matrix_tree_widget_stylesheet=("QTreeWidget{\n"
"    border:None;\n"
"    background-color: rgb(25, 26, 25);\n"
"    outline:none;"
"}\n"
"QTreeWidget:item:hover{\n"
"    background-color: rgb(46, 35, 52);\n"
"}\n"
"QTreeWidget:item:selected:active:hover{\n"
"    background-color: rgb(80, 45, 107);\n"
"}\n"
"QTreeWidget:item:selected:hover{\n"
"    background-color: rgb(46, 35, 52);\n"
"}\n"
"QTreeWidget:item:selected:active{\n"
"    background-color: rgb(80, 45, 107);\n"
"}\n"
"QTreeWidget:item:selected{\n"
"    background-color: rgb(41, 30, 47);\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QHeaderView::section{\n"
"    border:none;\n"
"    color: rgb(236, 236, 236);\n"
"    background-color: rgb(32, 33, 32);\n"
"    font: 11pt \"Alice\";\n"
"}\n"
"\n"
"/* VERTICAL */\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 11px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
number_of_matrix_label_stylesheet=("background-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:1, y2:0, stop:0 rgba(32, 33, 32, 255), stop:1 rgba(25, 26, 25, 255));\n"
"color: rgb(236, 236, 236);\n"
"border-bottom:0px;\n"
"border-left:0px;\n"
"border-top:0px;\n"
"border-style:solid;\n"
"border-left-color: rgb(85, 40, 107);\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:1, y2:0, stop:0 rgba(15, 16, 15, 255), stop:1 rgba(25, 26, 25, 255));\n"
"border-top-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:1, y2:0, stop:0 rgba(85, 40, 107, 255), stop:1 rgba(25, 26, 25, 255));\n"
"")
number_of_matrix_combobox_frame_stylesheet=("QFrame{\n"
"   background-color: rgb(25, 26, 25);\n"
"   color: rgb(236, 236, 236);\n"
"   selection-color: rgb(236, 236, 236);\n"
"   selection-background-color: rgb(52, 53, 52);\n"
"   outline: none;\n"
"   border:none"
"}\n"
"")
number_of_matrix_combobox_stylesheet=("QComboBox{\n"
"   background-color: rgb(25, 26, 25);\n"
"   color: rgb(236, 236, 236);\n"
"   selection-color: rgb(236, 236, 236);\n"
"   selection-background-color: rgb(52, 53, 52);\n"
"   outline: none;\n"
"   border:none"
"}\n"
"\n"
"/* VERTICAL */\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 9px;\n"
"    margin: 9px 0 9px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 9px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 9px;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 11px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")