background_decorative_slide_label_stylesheet=("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(24, 25, 24, 255), stop:1 rgba(27, 26, 25, 255));\n"
"border-style: solid;\n"
"border-top: None;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: rgb(18, 19, 18);")
choose_type_horizontal_slider_stylesheet=("QSlider{\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid;\n"
"background: rgb(15, 16, 15);\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.341, stop:0 rgba(0, 1, 0, 255), stop:1 rgba(15, 16, 15, 255));\n"
"border: 1px solid rgb(25, 26, 25);\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.341, stop:0 rgba(0, 1, 0, 255), stop:1 rgba(15, 16, 15, 255));\n"
"border: 1px solid rgb(25, 26, 25);\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(72, 73, 72, 255), stop:0.960227 rgba(60, 61, 60, 255));\n"
"border: 1px solid rgb(75, 76, 75);\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(84, 85, 84, 255), stop:0.960227 rgba(72, 73, 72, 255));\n"
"border: 1px solid rgb(87, 88, 87);\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
vector_import_label_stylesheet=("font: 8pt \"Alice\";\n"
"background-color: transparent;\n"
"color: rgb(126, 126, 126);")
vector_write_label_stylesheet=("font: 8pt \"Alice\";\n"
"background-color: transparent;\n"
"color: rgb(96, 96, 96);")
choose_vector_frame_stylesheet=("background-color: transparent;\n"
"color: rgb(236, 236, 236);")
choose_vector_combobox_x_stylesheet=("QComboBox{\n"
"    background-color: rgb(15, 16, 15);\n"
"    border:0px;\n"
"    color: rgb(236, 236, 236);\n"
"    selection-color: rgb(236, 236, 236);\n"
"    selection-background-color: rgb(52, 53, 52);\n"
"    font: 11pt \"Alice\";\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
choose_vector_combobox_y_stylesheet = choose_vector_combobox_x_stylesheet
values_chosen_x_label_stylesheet=("color: rgb(236, 236, 236);\n"
"font: 12pt \"Alice\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 16, 15, 255), stop:1 rgba(25, 26, 25, 255));")
values_chosen_y_label_stylesheet = values_chosen_x_label_stylesheet
angle_calculate_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(22, 23, 22);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(17, 18, 17);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(37, 38, 37);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(30, 31, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(29, 30, 29);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(22, 23, 22);\n"
"}    ")
dd_or_dms_horizontal_slider_stylesheet=("QSlider{\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid;\n"
"height: 7px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.341, stop:0 rgba(0, 1, 0, 255), stop:1 rgba(15, 16, 15, 255));\n"
"border: 1px solid rgb(47, 48, 47);\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.341, stop:0 rgba(0, 1, 0, 255), stop:1 rgba(15, 16, 15, 255));\n"
"border: 1px solid rgb(47, 48, 47);\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qradialgradient(spread:repeat, cx:0, cy:0.5, radius:0.128, fx:0, fy:0.5, stop:0 rgba(15, 16, 15, 244), stop:0.511364 rgba(72, 73, 72, 255), stop:1 rgba(15, 16, 16, 255));\n"
"border: 1px solid rgb(62, 63, 62);\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background:  qradialgradient(spread:repeat, cx:0, cy:0.5, radius:0.128, fx:0, fy:0.5, stop:0 rgba(27, 28, 27, 244), stop:0.511364 rgba(84, 85, 84, 255), stop:1 rgba(27, 28, 27, 255));\n"
"border: 1px solid rgb(73, 74, 73);\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
degrees_minutes_seconds_label_stylesheet=("font: 7pt \"Alice\";\n"
"color: rgb(126, 126, 126);\n"
"background-color:transparent;\n"
"border:0px;\n"
"margin:0px;")
decimal_degree_label_stylesheet=("font: 7pt \"Alice\";\n"
"color: rgb(96, 96, 96);\n"
"background-color:transparent;\n"
"border:0px;\n"
"margin:0px;")
angle_result_screen_scrollarea_label_stylesheet=("background-color: rgb(15,16,15);\n"
"font: 11pt \"Alice\";\n"
"color: rgb(236, 236, 236);\n")
write_vector_frame_stylesheet=("background-color: transparent;\n"
"color: rgb(236, 236, 236);")
write_vector_label_x_stylesheet=("color: rgb(236, 236, 236);\n"
"font: 11pt \"Alice\";\n"
"background-color: rgb(15,16,15);")
write_vector_label_y_stylesheet=("color: rgb(236, 236, 236);\n"
"font: 11pt \"Alice\";\n"
"background-color: rgb(15,16,15);")
decorative_write_x_label_stylesheet=("color: rgb(236, 236, 236);\n"
"font: 11pt \"Alice\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 16, 15, 255), stop:1 rgba(27, 28, 27, 255));")
decorative_write_y_label_stylesheet=("color: rgb(236, 236, 236);\n"
"font: 11pt \"Alice\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 16, 15, 255), stop:1 rgba(27, 28, 27, 255));")
write_vector_column_combobox_x_stylesheet=("QComboBox{\n"
"    background-color: rgb(27, 28, 27);\n"
"    border:0px;\n"
"    color: rgb(236, 236, 236);\n"
"    selection-color: rgb(236, 236, 236);\n"
"    selection-background-color: rgb(52, 53, 52);\n"
"    font: 11pt \"Alice\";\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
write_vector_column_combobox_y_stylesheet = write_vector_column_combobox_x_stylesheet