systemofequationschoosematrixListWidget_stylesheet = ("QListWidget{\n"
"    border:0px;\n"
"    color: rgb(96, 96, 96);\n"
"    font: 10.5pt \"Alice\";\n"
"    show-decoration-selected: 1;\n"
"    outline: 0;\n"
"}\n"
"QListView::item:alternate {\n"
"    background: #EEEEEE;\n"
"}\n"
"QListWidget::item:selected{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(72, 73, 72, 255), stop:1 rgba(62, 63, 62, 255));\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QListWidget::item:selected:active{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(72, 73, 72, 255), stop:1 rgba(62, 63, 62, 255));\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QListWidget::item:hover{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color:   qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(52, 53, 52, 255), stop:1 rgba(32, 33, 32, 255));\n"
"    color: rgb(156, 156, 156);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 7px;\n"
"    margin: 0px 0px 0px 0px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 0px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
systemofequationschoosevectorListWidget_stylesheet = ("QListWidget{\n"
"    border:0px;\n"
"    color: rgb(96, 96, 96);\n"
"    font: 10.5pt \"Alice\";\n"
"    show-decoration-selected: 1;\n"
"    outline: 0;\n"
"}\n"
"QListView::item:alternate {\n"
"    background: #EEEEEE;\n"
"}\n"
"QListWidget::item:selected{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(72, 73, 72, 255), stop:1 rgba(62, 63, 62, 255));\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QListWidget::item:selected:active{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(72, 73, 72, 255), stop:1 rgba(62, 63, 62, 255));\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QListWidget::item:hover{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color:   qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(52, 53, 52, 255), stop:1 rgba(32, 33, 32, 255));\n"
"    color: rgb(156, 156, 156);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 7px;\n"
"    margin: 0px 0px 0px 0px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 0px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
eigenvaluesresultscreen_scrollArea_stylesheet = ("QScrollArea{\n"
"    background-color: rgb(19, 20, 19);\n"
"    border:1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(25, 26, 25);\n"
"    font: 13pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
systemofequationsresultscrollArea_stylesheet = ("QScrollArea{\n"
"    background-color: rgb(19, 20, 19);\n"
"    border:1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(25, 26, 25);\n"
"    font: 13pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
systemofequationschoosevectorScrollArea_stylesheet = ("QScrollArea{\n"
"    background-color: rgb(19, 20, 19);\n"
"    border:1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(25, 26, 25);\n"
"    font: 13pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
systemofequationschoosematrixScrollArea_stylesheet = ("QScrollArea{\n"
"    background-color: rgb(19, 20, 19);\n"
"    border:1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(25, 26, 25);\n"
"    font: 13pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
eigenvalueschoosematrixListWidget_stylesheet = ("QListWidget{\n"
"    border:0px;\n"
"    color: rgb(96, 96, 96);\n"
"    font: 10.5pt \"Alice\";\n"
"    show-decoration-selected: 1;\n"
"    outline: 0;\n"
"}\n"
"QListView::item:alternate {\n"
"    background: #EEEEEE;\n"
"}\n"
"QListWidget::item:selected{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(72, 73, 72, 255), stop:1 rgba(62, 63, 62, 255));\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QListWidget::item:selected:active{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(72, 73, 72, 255), stop:1 rgba(62, 63, 62, 255));\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QListWidget::item:hover{\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    background-color:   qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(52, 53, 52, 255), stop:1 rgba(32, 33, 32, 255));\n"
"    color: rgb(156, 156, 156);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 7px;\n"
"    margin: 0px 0px 0px 0px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 0px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
eigenvalueschosenmatrixscreen_scrollArea_stylesheet = ("QScrollArea{\n"
"    background-color: rgb(19, 20, 19);\n"
"    border:1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(25, 26, 25);\n"
"    font: 13pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
screen_scrollArea_stylesheet = ("QScrollArea{\n"
"    background-color: rgb(19, 20, 19);\n"
"    border: 1px solid;\n"
"    border-color:rgb(25,26, 25);\n"
"    font: 13pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
draggablematrixListWidget_stylesheet = ("QListWidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(22, 23, 22, 255), stop:1 rgba(25, 26, 25, 255));\n"
"    border:0px;\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"    outline: none;\n"
"}\n"
"QListWidget:item:hover{\n"
"    background-color: rgb(46, 35, 52);\n"
"    border: 1px solid;\n"
"    border-color: rgb(46, 35, 52);\n"
"}\n"
"QListWidget:item:selected:active:hover{\n"
"    border: 1px solid;\n"
"    background-color: rgb(80, 45, 107);\n"
"    border-color: rgb(102, 42, 108);\n"
"}\n"
"QListWidget:item:selected:hover{\n"
"    border: 1px solid;\n"
"    background-color: rgb(46, 35, 52);\n"
"    border-color: rgb(56, 45, 62);\n"
"}\n"
"QListWidget:item:selected:active{\n"
"    border: 1px solid;\n"
"    background-color: rgb(80, 45, 107);\n"
"    border-color: rgb(80, 45, 107);\n"
"}\n"
"QListWidget:item:selected{\n"
"    border: 1px solid;\n"
"    background-color: rgb(41, 30, 47);\n"
"    border-color: rgb(41, 30, 47);\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 7px;\n"
"    margin: 0px 0px 0px 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 0px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
anglesscreen_scrollArea_stylesheet = ("QScrollArea{\n"
"    background-color: rgb(19, 20, 19);\n"
"    border: 1px solid;\n"
"    border-color:rgb(25,26, 25);\n"
"    font: 13pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
draggablevectorListWidget_stylesheet = ("QListWidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(22, 23, 22, 255), stop:1 rgba(25, 26, 25, 255));\n"
"    border:0px;\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"    outline: none;\n"
"}\n"
"QListWidget:item:hover{\n"
"    background-color: rgb(46, 35, 52);\n"
"    border: 1px solid;\n"
"    border-color: rgb(46, 35, 52);\n"
"}\n"
"QListWidget:item:selected:active:hover{\n"
"    border: 1px solid;\n"
"    background-color: rgb(80, 45, 107);\n"
"    border-color: rgb(102, 42, 108);\n"
"}\n"
"QListWidget:item:selected:hover{\n"
"    border: 1px solid;\n"
"    background-color: rgb(46, 35, 52);\n"
"    border-color: rgb(56, 45, 62);\n"
"}\n"
"QListWidget:item:selected:active{\n"
"    border: 1px solid;\n"
"    background-color: rgb(80, 45, 107);\n"
"    border-color: rgb(80, 45, 107);\n"
"}\n"
"QListWidget:item:selected{\n"
"    border: 1px solid;\n"
"    background-color: rgb(41, 30, 47);\n"
"    border-color: rgb(41, 30, 47);\n"
"    color: rgb(236, 236, 236);\n"
"    font: 10.5pt \"Alice\";\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    width: 7px;\n"
"    margin: 0px 0px 0px 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 0px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 10px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
eqstringtextEdit_stylesheet = ("QTextEdit {\n"
"    background-color: rgb(17, 18, 17);\n"
"    border:1px solid;\n"
"    border-color:rgb(35, 36, 35);\n"
"    font: 10.5pt \"Alice\";\n"
"    color: rgb(236, 236, 236);\n"
"    border-radius:5px;\n"
"    selection-background-color: rgb(85, 40, 107);\n"
"}\n"
"QTextEdit:hover {\n"
"    border: 1px solid;\n"
"    border-color: rgb(55, 56, 55);\n"
"    border-radius:5px;\n"
"}\n"
"    QTextEdit:focus {\n"
"    border-radius:5px;\n"
"    border-color:rgb(45, 46, 45);\n"
"}\n"
"    QTextEdit:focus:hover {\n"
"    border-color: rgb(55, 56, 55);\n"
"    border-radius:5px;\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {  \n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL     */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(5, 6, 5);\n"
"    height: 5px;\n"
"    margin: 0px 15px 0px 15px ;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR horizontal */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(72, 73, 72);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(72, 73, 72);\n"
"    width: 15px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(102,103, 102);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(85, 86, 85);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")