deg_and_rad_vertical_slider_stylesheet=("QSlider::groove:vertical {\n"
"border: 1px solid;\n"
"background: rgb(15, 16, 15);\n"
"width: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.341, stop:0 rgba(0, 1, 0, 255), stop:1 rgba(15, 16, 15, 255));\n"
"border: 1px solid rgb(25, 26, 25);\n"
"width: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.341, stop:0 rgba(0, 1, 0, 255), stop:1 rgba(15, 16, 15, 255));\n"
"border: 1px solid rgb(25, 26, 25);\n"
"width: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(72, 73, 72, 255), stop:0.960227 rgba(60, 61, 60, 255));\n"
"border: 1px solid rgb(75, 76, 75);\n"
"height: 13px;\n"
"margin-left: -2px;\n"
"margin-right: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(84, 85, 84, 255), stop:0.960227 rgba(72, 73, 72, 255));\n"
"border: 1px solid rgb(87, 88, 87);\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:vertical:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:vertical:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
degree_label_initial_stylesheet=("font: 8pt \"Alice\";\n"
"color: rgb(96, 96, 96);\n"
"background-color:transparent;\n"
"border:0px;\n"
"margin:0px;")
rad_label_initial_stylesheet=("font: 8pt \"Alice\";\n"
"color: rgb(126, 126, 126);\n"
"background-color:transparent;\n"
"border:0px;\n"
"margin:0px;")
tab_buttons_frame_stylesheet=("QFrame{\n"
"    background-color: rgb(127, 128, 127);\n"
"    border-left:None;\n"
"    border-right:1px;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:9px;\n"
"}")
vector_tab_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 36, 35);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(32, 33, 32);\n"
"    border-bottom:2px;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;\n"
"}    \n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:1, y2:0, stop:0 rgba(35, 36, 35, 255), stop:1 rgba(25, 26, 25, 255));\n"
"    margin-left: 3px;\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;    \n"
"}")
matrix_tab_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 36, 35);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(32, 33, 32);\n"
"    border-bottom:2px;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;\n"
"}    \n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:1, y2:0, stop:0 rgba(35, 36, 35, 255), stop:1 rgba(25, 26, 25, 255));\n"
"    margin-left: 3px;\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;    \n"
"}")
angles_tab_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 36, 35);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(32, 33, 32);\n"
"    border-bottom:2px;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;\n"
"}    \n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:1, y2:0, stop:0 rgba(35, 36, 35, 255), stop:1 rgba(25, 26, 25, 255));\n"
"    margin-left: 3px;\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;    \n"
"}")
eigenvalues_tab_button_sylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 36, 35);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(32, 33, 32);\n"
"    border-bottom:2px;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;\n"
"}    \n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:1, y2:0, stop:0 rgba(35, 36, 35, 255), stop:1 rgba(25, 26, 25, 255));\n"
"    margin-left: 3px;\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;    \n"
"}")
system_of_equations_tab_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 36, 35);\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);\n"
"    margin-right:0px;    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(32, 33, 32);\n"
"    border-bottom:2px;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;\n"
"}    \n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:1, y2:0, stop:0 rgba(35, 36, 35, 255), stop:1 rgba(25, 26, 25, 255));\n"
"    margin-left: 3px;\n"
"    border-bottom:2px;\n"
"    border-right:None;\n"
"    border-style:solid;\n"
"    border-color:rgb(15, 16, 15);    \n"
"    margin-right:0px;    \n"
"}")
filler_bottom_left_frame_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border: None;\n"
"    margin-right:0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 43, 42);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(39, 40, 39);\n"
"}    \n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:1, y2:0, stop:0 rgba(42, 43, 42, 255), stop:1 rgba(32, 33, 32, 255));\n"
"    margin-left: 3px;\n"
"}")
infoButton_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border:2px solid;\n"
"    border-color:rgb(25, 26, 25);    \n"
"    border-top-right-radius:13px;\n"
"    border-top-left-radius:13px;\n"
"    border-bottom-right-radius:13px;\n"
"    border-bottom-left-radius:13px;\n"
"    margin-right:0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(26, 54, 76);\n"
"    border:2px solid;\n"
"    border-color: rgb(29, 44, 55);    \n"
"    border-top-right-radius:13px;\n"
"    border-top-left-radius:13px;\n"
"    border-bottom-right-radius:13px;\n"
"    border-bottom-left-radius:13px;\n"
"    margin-right:0px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(29, 44, 55);\n"
"    border:2px solid;\n"
"    border-color:rgb(26, 54, 76);    \n"
"    border-top-right-radius:13px;\n"
"    border-top-left-radius:13px;\n"
"    border-bottom-right-radius:13px;\n"
"    border-bottom-left-radius:13px;\n"
"    margin-right:0px;\n"
"}    \n"
"")
assign_button_stylesheet=("QPushButton {\n"
"    background-color: rgb(25, 26, 25);\n"
"    border:None\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 36, 35);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(32, 33, 32);\n"
"}    ")
filler_top_left_frame_label_stylesheet=("background-color: rgb(25, 26, 25);\n"
"border-top:none;\n"
"border-left:none;\n"
"border-right:1px;\n"
"border-right-style:solid;\n"
"border-right-color:rgb(15, 16, 15);\n"
"border-bottom:1px;\n"
"border-bottom-style:solid;\n"
"border-bottom-color:rgb(15, 16, 15);\n"
            "")
right_all_clear_frame_stylesheet=("background-color: rgb(25, 26, 25);\n"
"border-left:1px;\n"
"border-style:solid;\n"
"border-color:rgb(15, 16, 15);\n"
"")
all_clear_button_stylesheet=("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:0, y2:1, stop:0 rgba(132, 43, 108, 255), stop:1 rgba(87, 40, 107, 255));\n"
"    border-top: 1px outset rgb(15, 16, 15);\n"
"    border-radius: 3px ;\n"
"    border-bottom: 1px outset rgb(15, 16, 15);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(232, 17, 35);\n"
"    border-top: 1px outset rgb(15, 16, 15);\n"
"    border-bottom: 1px outset rgb(15, 16, 15);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(149, 20, 30);\n"
"    border-top: 1px outset rgb(15, 16, 15);\n"
"    border-bottom: 1px outset rgb(15, 16, 15);\n"
"}    ")