matrix_vector_answer_equal_operators_stylesheet=("QPushButton {\n"
"    background-color: rgb(22, 23, 22);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(17, 18, 17);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(37, 38, 37);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(30, 31, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(29, 30, 29);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(22, 23, 22);\n"
"}    ")
general_operators_framestylesheet=("background-color: rgb(25,26,25);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: rgb(25,26, 25);\n"
"" )
generaloperatorsButtons_stylesheet = ("QPushButton {\n"
"    background-color: rgb(18, 19, 18);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(15,16,15);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(27, 28, 27);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(22, 23, 22);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(15, 16, 15);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(12, 13, 12);\n"
"}    ")
click_and_drag_labelstylesheet=("font: 8pt \"Alice\";\n"
"color: rgb(125, 80, 147);\n"
"background-color: rgb(22, 23, 22);\n"
"border:2px;\n"
"border-style: outset;\n"
"border-bottom: 0px;\n"
"border-color: rgb(19, 20, 19);\n"
"border-top-left-radius : 5px;\n"
"border-top-right-radius : 5px;\n"
"")
eq_string_text_edit_stylesheet=("QTextEdit {\n"
"background-color: rgb(25,26,25);\n"
"font: 10.5pt \"Alice\";\n"
"color: rgb(236, 236, 236);\n"
"}\n"
"QTextEdit:hover {\n"
"border: 1px solid;\n"
"border-color: rgb(0,140, 255);\n"
"}")
background_vectors_and_matrices_operators_label_stylesheet=("background-color: rgb(25, 26, 25);\n"
"border-left:2px;\n"
"border-right: 2px;\n"
"border-style:solid;\n"
"border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(32, 34, 32, 255), stop:1 rgba(25, 26, 25, 255));")